// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/home": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/home";
  };
  "routes/welcome-route.tsx": {
    id: "routes/welcome-route";
    page: "/";
  };
  "./routes/login-route.tsx": {
    id: "routes/login-route";
    page: "/login";
  };
  "./routes/home-route.tsx": {
    id: "routes/home-route";
    page: "/home";
  };
};